# Docker-compose for running multiple programming languages in a single compose environment
# in this docker-based local/remote (cloud) Integrated Development Environment (IDE)
version: "3.7"
services:
  c:
    image: c
    container_name: dev-env-c
    build:
      context: .
      dockerfile: docker/Dockerfiles/c.Dockerfile
    restart: unless-stopped
    # ports:
      ## Port Forward/Translate/Map from host system to container
      ## [host-ip-address]:[host-system-port]:[container-port]
    volumes:
      ## Mount volumes from host system into container
      ## [host-system-volume]:[container-volume]:[permissions]
      - ${PWD}/src/c:/src

