# Docker-compose for running multiple programming languages in a single compose environment
# in this docker-based local/remote (cloud) Integrated Development Environment (IDE)
version: "3.7"
services:
  rust:
    image: thanatisia/docker-ide:rust
    container_name: dev-env-rust
    restart: unless-stopped
    working_dir: /projects ## Set current working directory
    stdin_open: true # Equivalent to '-i' in 'docker run -itd'
    tty: true # Equivalent to '-t' in 'docker run -itd'
    # ports:
      ## Port Forward/Translate/Map from host system to container
      ## [host-ip-address]:[host-system-port]:[container-port]
    volumes:
      ## Mount volumes from host system into container
      ## [host-system-volume]:[container-volume]:[permissions]
      - ${PWD}/projects/rust:/projects
      - ${HOME}/.config:${HOME}/.config

